version: '3.9'


services:

  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app

  crud:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
