version: '3.9'

#volumes:
#  pgdata:

networks:
  dev_network:

services:

  app:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app

#    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres -d app" ]
#      interval: 30s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#      - ./logs:/var/log
    networks:
      - dev_network

  crud:
    build: .
    command: python3 server.py
    ports:
      - "8080:8080"
    volumes:
      - .:/crud
    depends_on:
      - app
    networks:
      - dev_network